### ISSUE TITLE
Idea: Twilio Notifier

### ISSUE THREAD

**Issue by scottconnerly** [pcarn/vaccine-watch#12]
Sends a text message from a provisioned Twilio number to your phone

**Comment by djsiroky** [comment]
I implemented a basic version of this in a fork here: https://github.com/djsiroky/vaccine-watch/commit/59ab73c6ec076088deb3f342978ac57a1b129e26

@pcarn I can do a PR on here if you're interested in adding that option. I've been using it to help inform family members in CA and IA about appointments. Right now the message content is pretty much the same as discord, but I could clean it up to be more text message friendly.

**Comment by pcarn** [comment]
Sure, PRs are welcome
