### ISSUE TITLE
KeyError: 'STATES'

### ISSUE THREAD

**Issue by DavidJamesAustin** [pcarn/vaccine-watch#13]
No matter how I do it, I can't get this to work in Heroku. I followed your directions and even tried a forked version without any changes... same error.

`
Mar 24 02:38:07 njvax app/clock.1 Traceback (most recent call last):
Mar 24 02:38:07 njvax app/clock.1   File "/app/clock.py", line 5, in <module>
Mar 24 02:38:07 njvax app/clock.1     from vaccine import check_for_appointments
Mar 24 02:38:07 njvax app/clock.1   File "/app/vaccine.py", line 14, in <module>
Mar 24 02:38:07 njvax app/clock.1     from notify import notify_available, notify_unavailable
Mar 24 02:38:07 njvax app/clock.1   File "/app/notify/__init__.py", line 5, in <module>
Mar 24 02:38:07 njvax app/clock.1     from .console import (
Mar 24 02:38:07 njvax app/clock.1   File "/app/notify/console.py", line 7, in <module>
Mar 24 02:38:07 njvax app/clock.1     states = json.loads(os.environ["STATES"])
Mar 24 02:38:07 njvax app/clock.1   File "/app/.heroku/python/lib/python3.9/os.py", line 679, in __getitem__
Mar 24 02:38:07 njvax app/clock.1     raise KeyError(key) from None
Mar 24 02:38:07 njvax app/clock.1 KeyError: 'STATES'`

**Comment by fstewart1986** [comment]
@DavidJamesAustin  what was the fix? I am encountering the same error.

**Comment by pcarn** [comment]
If you're getting `KeyError: 'STATES'` it means you don't have the environment variable `STATES` set.
https://github.com/pcarn/vaccine-watch#deployment-instructions

**Comment by fstewart1986** [comment]
@pcarn thank you.
