### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by fstewart1986** [pcarn/vaccine-watch#18]
Hi @pcarn, 

I am getting an ImportError when running console.py. 

Would you have insight this error?

    from . import NotificationMethod
ImportError: attempted relative import with no known parent package

**Comment by pcarn** [comment]
console.py is not a file to be run on its own. It's meant to be imported by the other files to log messages to the console.

The only file meant to be run is `python clock.py`, to start the process.
